name: CI (Main)

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  LIBURING_VERSION: "2.14"

jobs:
  build-and-test:
    runs-on: ubuntu-26.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: clang, cxx: clang++ }
          - { cc: gcc, cxx: g++ }
        sanitizer: [ tsan, asan ]

    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout Liburing to Specified Version
        run: |
          cd ./third_party/liburing
          git fetch --tags
          git checkout liburing-${{ env.LIBURING_VERSION }}
          cd ../../

      # GCC 15 Regression https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124584
      - name: Install GCC 14
        if: matrix.compiler.cc == 'gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          gcc --version

      - name: Configure CMake
        run: |
          COMPILER=$(${{matrix.compiler.cc}} --version | head -n 1)
          echo "Using compiler: $COMPILER"
          SANITIZER_FLAG=""
          if [ "${{ matrix.sanitizer }}" = "tsan" ]; then
            SANITIZER_FLAG="-DCONDY_TESTS_TSAN=ON"
          elif [ "${{ matrix.sanitizer }}" = "asan" ]; then
            SANITIZER_FLAG="-DCONDY_TESTS_ASAN=ON"
          fi
          cmake -B ${{github.workspace}}/build \
              -DCONDY_BUILD_EXAMPLES=ON \
              -DCONDY_BUILD_BENCHMARKS=ON \
              -DCONDY_BUILD_TESTS=ON \
              $SANITIZER_FLAG \
              -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} \
              -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j$(nproc)

      - name: Run Tests
        timeout-minutes: 5
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose

      - name: Run Benchmarks
        timeout-minutes: 5
        working-directory: ${{github.workspace}}
        run: bash scripts/run-bench.sh -t 60 build/benchmarks
